version: '3.8'

services: 

  node:
    image: node:15.5.0-stretch
    hostname: ${PROJECT_NAME}-node
    container_name: ${PROJECT_NAME}-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./code:/app
      - /app/node_modules
    ports:
      - ${WEB_PORT}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true